### PR TITLE
[bug fix] fix "link 2005" error in msvc

### PR DESCRIPTION
**Pull request by ChaoII**

### CODE REVIEW

**Comment by QxOrm** [comment]
Hello,
This modification fixes issues #62, #65 and #89 ?

If yes, this is strange because I don't have to do that on my environment.

**Comment by ChaoII** [comment]
> Hello, This modification fixes issues #62, #65 and #89 ?
> 
> If yes, this is strange because I don't have to do that on my environment.

yes. 
This is really strange，but it does solve my problem. Maybe you  can try to compile QxOrm on a pure Windows computer to reproduce this problem.

**Comment by QxOrm** [comment]
Ok thx for the info :)

**Comment by QxOrm** [comment]
Done in latest commit

**Pull request closed without merging**
