### PR TITLE
fix QT version checking macros

### PR DESCRIPTION
**Pull request by stharward**
#if (QT_VERSION < 0x051500)

is very different from

 #if (QT_VERSION < QT_VERSION_CHECK(5,15,0))

because 0x051500 != ((5<<15) + (15<<8) + (0)), which is how Qt calculates QT_VERSION.  See qglobal.h.

This correction uncovered a bug in src/QxDao/QxSqlRelationLinked.cpp, where some template arguments were missing.

Also corrected the version checks for QLinkedList. This class was deprecated in 5.15.0, and QxOrm was checking against 6.0.0

### CODE REVIEW

**Comment by QxOrm** [comment]
Hello,

Thx you are right : 0x051500 doesn't mean 5.15 Qt version because this is not an hexa value.
But I read also that it can have some issue with QT_VERSION_CHECK macro and the moc.

All checks in QxOrm library should be OK until 5.9 Qt version (because hexa value equals to decimal value).
So I would prefer to not use the QT_VERSION_CHECK macro and convert every check after 5.9 version to the hexa value.

**Comment by stharward** [comment]
> But I read also that it can have some issue with QT_VERSION_CHECK macro and the moc.

That was a problem with the Qt4 MOC, but hasn't been a problem since Qt5. QT_VERSION_CHECK is the canonical way to do the check. It will function even if Qt changes the internal format of the version specifier.

**Comment by QxOrm** [comment]
I have some customers who are still using Qt4 : this is why I would prefer to change some version checks to hexa value.

**Comment by stharward** [comment]
> I have some customers who are still using Qt4 : this is why I would prefer to change some version checks to hexa value.

Updated the branch to use hex values instead of the macro. Few other bug fixes too.

**Comment by QxOrm** [comment]
> Updated the branch to use hex values instead of the macro
Thank you very much, I will take a look on that when I will have some time :)

**Comment by QxOrm** [comment]
Done in the latest commit.
Finally, I used QT_VERSION_CHECK, and for Qt4 I redefine this macro : I have tested it and this is working fine, thx !

**Pull request closed without merging**
